### ISSUE TITLE
Recommendation: Add the ability to diff public IPs agains DNS records 

### ISSUE THREAD

**Issue by ammarion** [ovotech/domain-protect#17]
1- For each hosted zone id do `list_resource_record_sets` for A records and only store public IPs in your list
2- Describe instances and get public IPs and add the the list 
3- Describe elastic IPs and add to the list
4- Describe ENIs i.e ec2.describe_network_interfaces().get("NetworkInterfaces") and get public IPs, add to the list

finally, diff and if IP exist in route53 but the not in your list of public IPs, you have found a record to remove.

**Comment by ammarion** [comment]
There is a concern is that this approach is likely to result in numerous false positives - in some cases, there are DNS A records in one AWS account which point to an IP address on-premise, or in another AWS account, or in GCP, or even at a third party.

**Comment by paulschwarzenberger** [comment]
@ammarion this is now implemented - once we started using DynamoDB databases, it became feasible. As well as the features you suggested, we've also added Global Accelerator IP addresses. Currently it's an optional feature which you have to turn on by setting a variable - full details in the documentation.
