### ISSUE TITLE
Output no domain found in this account error

### ISSUE THREAD

**Issue by ammarion** [ovotech/domain-protect#34]
The domain-protect-ns-domain-default lambda should print a message that let the admin know that a given account doesn' have registered domains. Not a dealbreaker, but good to have and easy to do as the script has all the information needed.

**Comment by paulschwarzenberger** [comment]
agreed, this would be useful

**Comment by paulschwarzenberger** [comment]
I've added this, along with improved error handling: https://github.com/ovotech/domain-protect/pull/35
