### ISSUE TITLE
Getting error AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by nadxtract** [ovotech/domain-protect#39]
When i run  
-aws-cname-cloudfront-s3.py  
-aws-cname-s3.py  
-aws-ns-domain.py  
-aws-ns-subdomain.py 

I get the below error 

```
 File "/home/homefolder/.local/lib/python3.5/site-packages/dns/resolver.py", line 32, in <module>
    import dns.flags
  File "/home/homefolder/.local/lib/python3.5/site-packages/dns/flags.py", line 24, in <module>
    class Flag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by paulschwarzenberger** [comment]
Hi, are you testing from a locked down laptop or within a corporate network? I've had issues with DNS resolution in some corporate networks, so I'd recommend a direct Internet connection from an unrestricted laptop. Also, the code has only been tested with Python 3.8 / 3.9 so you may want to try upgrading your Python.

**Comment by paulschwarzenberger** [comment]
please try with updated Python code for manual scans https://github.com/ovotech/domain-protect/pull/42
